version: "3"
services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
  prism:
    platform: linux/amd64
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.yml'
    volumes:
      - ./schema/api.yml:/tmp/api.yml:ro
    ports:
      - 4010:4010
