name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE*'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: miuchi-net
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .

