name: Generate Documents

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/generate-documents.yml'
      - 'schema/api.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: miuchi-net
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix profile install nixpkgs#nodejs
      - name: build documents
        run: |
          cd schema
          npx @redocly/cli build-docs ./api.yml -o dist/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./schema/dist
          destination_dir: .
          keep_files: true

